version: '3.8'

services:
  telegraf:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8094:8094"
    environment:
      - TELEGRAF_DEBUG=true
