[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = true

[[inputs.mqtt_consumer]]
  # Change this to your MQTT broker address
  servers = ["tcp://146.190.151.81:1883"]
  topics = ["milesight/uplink"]
  username = "guest"
  password = "guest"
  data_format = "json"
  tag_keys = ["devEUI", "deviceName", "timeZone"]
  name_override = "milesight_mqtt"

# [[processors.execd]]
#   command = ["/usr/local/bin/milesight_processor", "-config", "/etc/telegraf/milesight_processor.conf"]
#   namepass = ["milesight_mqtt"]

[[outputs.file]]
  files = ["stdout"]
